# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        DATABASE_CONNECTION: "mysql://bb7f8060e16a1c:7af9692b@us-cdbr-east-02.cleardb.com/heroku_e4eae8d9e5d0946?reconnect=true"
        MAIL_HOST: "smtp-relay.sendinblue.com"
        MAIL_PASS: "LsFaWMGgZwctjJ62"
        MAIL_PORT: 587
        MAIL_USER: "alex.cst.reis@gmail.com"

